name: iiGenomes-build
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::star=2.6.0c
  - bioconda::hisat2=2.1.0
  - bioconda::salmon=0.11.0
  - bioconda::ucsc-genepredtogtf=366
  - bioconda::kallisto=0.44.0
  - bioconda::samtools=1.9
  - bioconda::fastqc=0.11.7
  - bioconda::bbmap=38.06
  - bioconda::bowtie2=2.3.4.1
  - bioconda::seqtk=1.3
  - bioconda::bwa=0.7.17
  - bioconda::tophat=2.1.1
  - bioconda::bioconductor-genomicfeatures=1.30.3
  - conda-forge::zip=3.0
  - bioconda::rsem=1.2.28
  - bioconda::cufflinks=2.2.1
  - bioconda::bowtie=1.2.2
  - bioconda::seqkit=0.9.1